#! /usr/bin/env python3

# 'q' - quit
# 'p' - print
# 'd' - delete
# 's' - substitute (g permitted)
# -n -  stops input lines being printed by default

# command 0-> argss
# read from standard input

import re


def quit(options, regex, input):
    pass


def print():
    pass


def delete():
    pass


def sub():
    pass
